export interface Fundraiser {
  id: string,
  name: string,
  activeFrom: number,
  activeTo?: number,
  paused: boolean,
  totalRaised: number,
  goal: number,
  matchFundingRate?: number,
  matchFundingPerDonationLimit?: number,
  matchFundingRemaining?: number,
  minimumDonationAmount?: number,
  groupsWithAccess: string[],
}

export interface Donation {
  id: string,
  fundraiserId: string,
  name: string,
  email: string,
  createdAt: number,
  address?: string,
  giftAid: boolean,
  comment: string,
  donationAmount: number,
  matchFundingAmount: number,
  contributionAmount: number,
  payments: { at: number, amount: number }[],
  paymentMethod: "card",
  paymentGatewayId?: string,
  charity: string,
  overallPublic: boolean,
  namePublic: boolean,
  commentPublic: boolean,
  donationAmountPublic: boolean,
}
