import Helmet from 'react-helmet';

import { FormProvider, useForm } from 'react-hook-form';
import Page from './Page';
import Section, { SectionTitle } from './Section';
import Navigation from './Navigation';
import FAQs, { FAQ } from './FAQs';
import Footer from './Footer';

import IntroStats from './IntroStats';
import Link from './Link';
import Quote from './Quote';
import { LabelledInput } from './Form';

import { Brand } from '../helpers/types';

// Generated by column W in https://docs.google.com/spreadsheets/d/1uCbQW9_XonHsq_ibD5zxm7eWLKLaWHTwF-mkad6Wg88/edit
const ALL_ENTRIES = [
  {
    id: '01G9ZWEBTMZKH7E83F0BTJSETK', name: 'Florine Rombach, Physics (DPhil) Student', chapter: 'Oxford', year: 2022, quote: "Raise empowered me to make a financial difference through charitable giving - I'm not not sure why I didn't realise earlier that this was something I could budget for and enjoy!",
  },
  {
    id: '01G9ZWEBTFKS7Y64JVCJF96TC7', name: 'Ben Stewart, Economics Student @ Hatfield College', chapter: 'Durham', year: 2022, quote: 'Raise helped brake the cycle of guilt that had been pushing me away from giving and instead made it fantastic fun!', img: '/shared/images/yearbook/01G9ZWEBTFKS7Y64JVCJF96TC7.jpg',
  },
  {
    id: '01G9ZWEBTMTEAREJ85JS1CMAYJ', name: 'Robyn Glover-Trigger, History Student @ Keble', chapter: 'Oxford', year: 2022, quote: 'I wanted to be a part of a charity that I believe in an trust. Raise is an incredible organisation and it’s something I’m proud to talk to people about.',
  },
  {
    id: '01G9ZWEBTMF998TZ4V9HB5Y99H', name: 'Yetunde Kehinde, Geography Student @ Keble', chapter: 'Oxford', year: 2022, quote: 'Just doing my part :)',
  },
  {
    id: '01G9ZWEBTFM7FJ25GTTBPE4MNN', name: 'Helen Tyler-Cole, History Student @ Hatfield College', chapter: 'Durham', year: 2022, quote: "All charitable giving should be a rewarding and highly effective enterprise and, at it's core, that is what Raise does.", img: '/shared/images/yearbook/01G9ZWEBTFM7FJ25GTTBPE4MNN.jpg',
  },
  {
    id: '01G9ZWEBTFSWWBS1DXAYETWQYY', name: 'Lynette Koh, Law Student @ St John’s College', chapter: 'Durham', year: 2022, quote: 'I wanted to change the way people approach charity! Raise’s ethos has inspired me and I had hoped to inspire those around me to donate deliberately.', img: '/shared/images/yearbook/01G9ZWEBTFSWWBS1DXAYETWQYY.jpg',
  },
  {
    id: '01G9ZWEBTMCXSQ4K1A7QDV9V81', name: 'Jacob Milikan, History Student @ St Anne’s', chapter: 'Oxford', year: 2022, quote: 'Raise’s emphasis on giving being a celebration rather than a sacrifice really resonated with me. I believe this is a mindset that should be widely adopted.',
  },
  {
    id: '01G9ZWEBTFJKX9NMSAA7MYESD2', name: 'Nav Aithanj, Anthropology and Economics Student @ Castle', chapter: 'Durham', year: 2022, quote: 'Raise is the ideal way to let your donation have the greatest impact possible on the world, and also on you, through its focus on conscious giving.', img: '/shared/images/yearbook/01G9ZWEBTFJKX9NMSAA7MYESD2.jpg',
  },
  {
    id: '01G9ZWEBTFYFBQBY82X9PHXWCT', name: 'Bethany Mellody, Politics and International Relations Student @ Ustinov College', chapter: 'Durham', year: 2022, quote: "Raise is a fantastic organisation. To be even a minor part of Raise's achievements this year is an honour.", img: '/shared/images/yearbook/01G9ZWEBTFYFBQBY82X9PHXWCT.jpg',
  },
  {
    id: '01G9ZWEBTMGV6S940ZVWSVJA8R', name: 'Jake Mendel, Graduate Entry Medicine Student @ Worcester', chapter: 'Oxford', year: 2022, quote: 'I’ve been involved in Raise for 5 years and it’s so lovely to see the movement continuing to grow!',
  },
  {
    id: '01G9ZWEBTMC6TNDK0TSTVY5FX2', name: 'Reef Ronel, Medicine Student @ Jesus', chapter: 'Oxford', year: 2022, quote: "I was the VP for Fundraising last year, and though I wasn't involved in committee this year I still think it's a fantastic movement",
  },
  {
    id: '01G9ZWEBTFSAEQP9F0RS7PMAV0', name: 'Alex Greer, Chemistry Student @ Van Mildert', chapter: 'Durham', year: 2022, quote: 'Raise is an opportunity to join a community of like-minded students to donate a meaningful sum of money to a effective cause, which makes a real difference.', img: '/shared/images/yearbook/01G9ZWEBTFSAEQP9F0RS7PMAV0.jpg',
  },
  {
    id: '01G9ZWEBTFXDJ1BK0TERMJC99Y', name: 'Elena Caspall, History and English Student @ Grey College', chapter: 'Durham', year: 2022, quote: "I joined Raise because of its unique philosophy and celebratory approach to giving. It's an amazing community and I can't wait to see what it will do next year!", img: '/shared/images/yearbook/01G9ZWEBTFXDJ1BK0TERMJC99Y.jpg',
  },
  {
    id: '01G9ZWEBTM9V944JMVX536EEH2', name: 'Theo Sergiou, Philosophy Politics Economics Student @ Keble', chapter: 'Oxford', year: 2022, quote: 'I think I thought it was very easy to get sucked in, not just in Oxford but for anyone in life, whilst Raise seemed to be a paperweight to what really matters in life. I believe no where is more effective that Raise in Oxford to spend my time with as well as a beautiful group of people.',
  },
  {
    id: '01G9ZWEBTF3GFNRDC4TXPGKFVM', name: 'Alison Greenfield, Hatfield College', chapter: 'Durham', year: 2022, quote: 'Being a representative of Raise Durham has been a memorable experience! Making a positive impact locally and globally is at the heart of what makes this movement great.', img: '/shared/images/yearbook/01G9ZWEBTF3GFNRDC4TXPGKFVM.jpg',
  },
  {
    id: '01G9ZWEBTFY09AMNT98MATHW02', name: 'Kyla, Law Student @ Hatfield College', chapter: 'Durham', year: 2022, quote: 'I wanted to get involved with a new community at university, and thought Raise would be a great way to do this whilst also making a wider impact!', img: '/shared/images/yearbook/01G9ZWEBTFY09AMNT98MATHW02.jpg',
  },
  {
    id: '01G9ZWEBTME1BFH3CSTB93367H', name: 'Eloise Holland, Maths and Computer Science Student @ Oriel', chapter: 'Oxford', year: 2022, quote: "I joined Raise because I'm passionate about effective altruism. I love that it not only celebrates giving but also informs students about how to make effective and meaningful donations in future!",
  },
  {
    id: '01G9ZWEBTHT0HF7VDK5HQB5RXS', name: 'Tabitha Awre, English Student @ Fitzwilliam', chapter: 'Cambridge', year: 2022, quote: 'Really glad to see that there is a less bourgeoise side to Cambridge and that there is a push for inclusivity. Thanks for making such a welcoming event!',
  },
  {
    id: '01G9ZWEBTGFAVAN3KPNYB8E3F4', name: 'Juanita Virk, Medicine Student @ Magdalene', chapter: 'Cambridge', year: 2022, quote: 'I chose to join MWA because I support their ethos of thoughtful and intentional giving.',
  },
  {
    id: '01G9ZWEBTH3874NJRAWBP286B6', name: 'Alex Macpherson, History and Modern Languages Student @ Fitz', chapter: 'Cambridge', year: 2022, quote: "I've really enjoyed getting to know the effective giving community in Cambridge for the past two years as a member of One for the World. MWA struck me as a great opportunity to come together and celebrate, while also making a real difference to people's lives!",
  },
  {
    id: '01G9ZWEBTHT0DX51KVWQ9N00KX', name: 'Nandini Shiralkar, Engineering Student @ Trinity', chapter: 'Cambridge', year: 2022, quote: 'I have never needed a reason to get involved with charitable initiatives: it’s just so intrinsic to who I am as a person and the way I see the world that it comes almost naturally. I find it really fascinating how one can have a significant impact through effective charitable giving.',
  },
  {
    id: '01G9ZWEBTMF2Q1FW4NA33JMT2G', name: 'Kirish Rajaseelan, Medicine Student @ Queens’', chapter: 'Cambridge', year: 2022, quote: 'Rahul shah',
  },
  {
    id: '01G9ZWEBTHRTN8755C6VR7X2SR', name: "Holly Richards, English Student @ Christ's", chapter: 'Cambridge', year: 2022, quote: 'I initially decided to join MWA in my first year to be part of a positive and meaningful community, where giving is celebrated. I enjoyed it so much that this year I became part of the committee as one of the events team, which has been such a rewarding experience, and I would definitely recommend it to anyone thinking of getting involved!',
  },
  {
    id: '01G9ZWEBTMBA6W35QA6RAKCCTR', name: "Tanya Kuzmich, Medicine Student @ St Edmund's", chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTGMBYCJS4R58CJ1PE1', name: 'Anonymous, Natural Sciences (physical) Student @ Jesus', chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTGW364RTVC3Z1ZDV6X', name: 'Anonymous, Veterinary Medicine Student @ Queens’', chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTH3MSEN6EBXN1AJ3C9', name: 'Jyothi Cross, HSPS Student @ Catz', chapter: 'Cambridge', year: 2022, quote: 'I feel so gross and wrong spending money on going to extravagant events whilst people around the world are still suffering under structural conditions like lack off medical care, social security, and sustainable food and shelter. I really wanted to give something back, so I could spend the time with my friends at a may ball but balance out my impact.',
  },
  {
    id: '01G9ZWEBTGRWMBBBYERAG4P98D', name: 'Lucas Pringle, English Literature Student @ Gonville and Caius', chapter: 'Cambridge', year: 2022, quote: 'Having heard so much about MWA from my college wife (shoutout to Georgia Brown!) I knew how good of a cause MWA was, and how lovely this garden party would be :)',
  },
  {
    id: '01G9ZWEBTGWQRNMK6B70GN48AV', name: 'Anonymous, History Student', chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTHP60KAE0HTJXSY2GA', name: "Sophie Clare, MML (French & German) Student @ Christ's", chapter: 'Cambridge', year: 2022, quote: 'I knew several friends on the MWA committee who found it really rewarding, so I was enthusiastic to donate and support the initiative - especially given the emphasis on finding community and celebrating the positive achievements of charitable donations. I hope to get more involved in the future.',
  },
  {
    id: '01G9ZWEBTHZM4BZX9DVAQM2XAC', name: 'Emily Beatty, Mathematics Student @ Trinity', chapter: 'Cambridge', year: 2022, quote: "MWA helps me realise the impact of the resources I have and my ability to improve others' lives.",
  },
  {
    id: '01G9ZWEBTH45ZDEMQ7BVERJPAJ', name: "Shaimerden Abekov, Engineering Student @ King's", chapter: 'Cambridge', year: 2022, quote: 'Matched donations and my friends joining it!',
  },
  {
    id: '01G9ZWEBTMHB21H54TC023DP27', name: 'Euan Ong, Computer Science Student @ Trinity', chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTG99TVG3TWG0P1ZCTE', name: 'Sarah Adegbite, Theology Student @ St John’s', chapter: 'Cambridge', year: 2022, quote: 'I recognise the immense privilege I have to live in a secure environment with free and easy access to healthcare. I wanted to give back in gratitude and proactive care for those less fortunate.',
  },
  {
    id: '01G9ZWEBTHXXWV42A4WR8HVKYG', name: 'Ella Shattock, English Student @ Sidney Sussex', chapter: 'Cambridge', year: 2022, quote: 'The persuasion of the one and only Keely Price is the real reason that I joined MWA — but also just because it’s a great cause.',
  },
  {
    id: '01G9ZWEBTMJYB8X2TJRBCWADZN', name: 'Aman Vernekar, Engineering Student @ Selwyn', chapter: 'Cambridge', year: 2022, quote: "MWA's positive messaging and focus on effective giving really appealed to me. I'll be honest, I thought long and hard before deciding to make a weekly donation since it was the first time I was donating a significant amount of money but it is now the only time I feel good seeing money leave my account.",
  },
  {
    id: '01G9ZWEBTFW571XTWH51AFHEBF', name: 'Anonymous, Philosophy Student @ Hild & Bede College', chapter: 'Durham', year: 2022,
  },
  {
    id: '01G9ZWEBTHXFRJQ4HWRCKTF49M', name: 'Anna Nichols, HSPS Student @ Trinity Hall', chapter: 'Cambridge', year: 2022, quote: "It's really meaningful to give something back to society, and the AMF is such an efficient way of helping many people",
  },
  {
    id: '01G9ZWEBTM99XEXBQ3X8C39RPW', name: "Jamie Barrett, Natural Sciences (Physical) Student @ Christ's College", chapter: 'Cambridge', year: 2022, quote: 'To me, MWA is a chance to see real change in the community and the world.',
  },
  {
    id: '01G9ZWEBTGB58AQ5BV1HSS2VGH', name: 'Anonymous, Mathematics Student @ Trinity', chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTGD90AR4F6ZY7WHXRT', name: 'Cindy Wu, Engineering Student @ St. John’s', chapter: 'Cambridge', year: 2022, quote: 'It means concern and compassion for those less fortunate, acknowledgement of my privilege, and honouring my personal values and motivations in life - to make the world a better place',
  },
  {
    id: '01G9ZWEBTHK5BM1TEP4GN9TBF5', name: 'Dhruv Makwana, CompSci (PhD) Student @ Trinity', chapter: 'Cambridge', year: 2022, quote: "Don't need no May Balls",
  },
  {
    id: '01G9ZWEBTG4WJTFXXDPTAXKPC7', name: 'Samyak Jain, Mathematics Student @ Queens', chapter: 'Cambridge', year: 2022, quote: 'Friends. a lot',
  },
  {
    id: '01G9ZWEBTGTJQCBSHE2CE8QM57', name: 'Anonymous, Economics Student @ Queens’', chapter: 'Cambridge', year: 2022, quote: 'MWA is an amazing group of people who try to have as much of an impact as possible!',
  },
  {
    id: '01G9ZWEBTHH6Y3825SQE5FHJRR', name: 'Thomas Niblett, HSPS Student @ Selwyn', chapter: 'Cambridge', year: 2022, quote: 'A good way to fight back against the wealth, power and privilege of Cambridge',
  },
  {
    id: '01G9ZWEBTHM00EBWCYN0SGN5ZP', name: 'Rohan Gupta, Economics Student @ Churchill', chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTHMRH8NGMZ5CF7ZV61', name: 'Rhiannon Warren, Anglo-Saxon, Norse and Celtic Student @ Trinity Hall', chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTHVAR6G4QB6WF20BFB', name: 'Sam Webber, Natural Sciences Student @ Churchill', chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTMQ91ABBSVP8KQVBNE', name: 'Preena Shah, Natural Sciences Student @ Churchill College', chapter: 'Cambridge', year: 2022, quote: 'Such an incredible community - the power of conscious and collaborative giving is unbeatable!',
  },
  {
    id: '01G9ZWEBTH0GX7VF8CTNTC2H6G', name: "Amartya Maheshwari, Economics Student @ St John's", chapter: 'Cambridge', year: 2022, quote: "Because it's a great cause and because the Great Neek Rohan Shah told me to.",
  },
  {
    id: '01G9ZWEBTFT2PCF459RXCK9BDZ', name: 'Emma Riley, History Student @ Trevelyan College', chapter: 'Durham', year: 2022, quote: 'I wanted to be part of a community focused on make the largest impact possible, centred on celebration.',
  },
  {
    id: '01G9ZWEBTHKXEW7CEV7DTK2PM5', name: 'Miriam Lay, Linguistics Student @ Fitzwilliam', chapter: 'Cambridge', year: 2022, quote: "I'm glad to be part of something that makes the Cambridge experience not just about expensive parties but also about doing something good!",
  },
  {
    id: '01G9ZWEBTFTKC746VG6QS99T9W', name: 'Anonymous, Law Student @ Ustinov College', chapter: 'Durham', year: 2022, quote: "I joined raise because it's approach to charity work seemsled fresh and effective. I'm glad to have participated this academic year.",
  },
  {
    id: '01G9ZWEBTH1YEZHE2B7YZB8PK6', name: 'Miriam Butcher, Law Student @ Trinity Hall', chapter: 'Cambridge', year: 2022, quote: 'I was drawn in by the fun everyone involved seemed to be having while effectively raising money! Joining the committee has really made my year',
  },
  {
    id: '01G9ZWEBTHDZ4672Z3MCZGHVTY', name: 'Sophia Bor, Theology Student @ Murray Edwards', chapter: 'Cambridge', year: 2022, quote: 'In all honesty, I originally joined MWA because many of my friends were, but as I learn more about it over the years, I become more and more excited to be a part of it! I love the idea that we should think about giving charity whilst enjoying ourselves during May week, the fact that everyone comes together at the party to celebrate giving, and also really see the value in giving to a high-impact charity.',
  },
  {
    id: '01G9ZWEBTMWEK9HAHR5191VEP7', name: 'Ruby Cline, HSPS Student @ Murray Edwards', chapter: 'Cambridge', year: 2022, quote: "Often, students don't realise the power we have to do good. I joined MWA because I needed a reminder!",
  },
  {
    id: '01G9ZWEBTMG6Q9XSGBZ9A99TZY', name: 'Jorja Korosec, History Student @ Queens’', chapter: 'Cambridge', year: 2022, quote: 'MWA helps people to make a significant impact on the world around them, generates a positive mindset and helps me feel part of a strong community full of great people.',
  },
  {
    id: '01G9ZWEBTH4309TXF3R58XQPSC', name: "Majid Panahi, Management Studies Student @ King's", chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTHGM3WQTF6C9JX33MW', name: 'Pranay Mittal, Theology Student @ Trinity College', chapter: 'Cambridge', year: 2022, quote: "It's wonderful to join a community of people who care this much about improving people's lives.",
  },
  {
    id: '01G9ZWEBTHZFS9Q91SJ5QX2R12', name: 'Samuel Lachmann, Astrophysics Student @ Jesus', chapter: 'Cambridge', year: 2022, quote: 'To join a community of people passionate about improving the world we live in.',
  },
  {
    id: '01G9ZWEBTHTSSZA07EQGJK1VCX', name: "Carrie Day, Natural Sciences (Biological) Student @ Christ's College", chapter: 'Cambridge', year: 2022, quote: "I am Zimbabwean and so know the impact malaria can have on a country. I've also begun to think more about the value of money the difference it can make when it's used thoughtfully.",
  },
  {
    id: '01G9ZWEBTHN6BRH1D0WP0GFKVN', name: 'Elizaveta Stetsenko, Law Student @ Sidney Sussex', chapter: 'Cambridge', year: 2022, quote: 'I’ve joined MWA because giving to those who need it makes everyone happier.',
  },
  {
    id: '01G9ZWEBTGD1C1SE6KNF5MNM6K', name: 'Anonymous, Natural Sciences Student @ Trinity Hall', chapter: 'Cambridge', year: 2022, quote: 'Recommended by friends on committee as well as wanting to take part in charitable endeavour',
  },
  {
    id: '01G9ZWEBTH7R8EDVV47JH74Q92', name: 'Gábor Fuisz, Computer Science Student @ Churchill College', chapter: 'Cambridge', year: 2022, quote: 'I would prefer people not dying of malaria. (Or any other thing, for the record, but I only have so much money.)',
  },
  {
    id: '01G9ZWEBTH0YXM17PN9HAXAQXP', name: 'Rudolf Laine, Computer Science Student @ Trinity', chapter: 'Cambridge', year: 2022, quote: 'Positive impact',
  },
  {
    id: '01G9ZWEBTMF0YE8XSP2VGDAYQP', name: 'Neha, Mathematics and Statistics Student @ Keble', chapter: 'Oxford', year: 2022, quote: 'Great',
  },
  {
    id: '01G9ZWEBTHPET32P0E9EGNK4H8', name: "Pippa Prendergast-Coates, English Student @ Christ's", chapter: 'Cambridge', year: 2022, quote: 'A fantastic chance to celebrate and do good with friends.',
  },
  {
    id: '01G9ZWEBTH81625JMEFPZGS84P', name: "Daniel Turaev, Maths Student @ St Catharine's", chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTHETRGNTXHP0SYXFDD', name: 'Jack Lubner, History Student @ Trinity Hall', chapter: 'Cambridge', year: 2022, quote: 'Being part of the MWA team was one of the most rewarding and impactful things I’ve done. Knowing that you’re genuinely making a difference is unbelievably special.',
  },
  {
    id: '01G9ZWEBTMNFNBPFY98KATDP3G', name: 'Agno Kachappilly Shaiju, Biological Natural Sciences Student @ Churchill', chapter: 'Cambridge', year: 2022, quote: 'MWA is an impactful way to donate to charity and as a community make a large difference to many lives.',
  },
  {
    id: '01G9ZWEBTGYGX0W1QMPS923JCX', name: 'Anonymous, English Student @ Murray Edward', chapter: 'Cambridge', year: 2022, quote: 'Amazing to have a charity opportunity in the context of May Week.',
  },
  {
    id: '01G9ZWEBTGHQBMSKVBWG7V5P0D', name: 'Michael Kohn, Mathematics Student @ Pembroke', chapter: 'Cambridge', year: 2022, quote: "I really liked the idea of rather than using Cambridge's immense wealth for a one-night party solely for members already at Cambridge, to use money meaningfully and with a lasting impact to do something good!",
  },
  {
    id: '01G9ZWEBTGT6V90FMG9JSMPB0F', name: "Anonymous, Theology & Religion Student @ Christ's", chapter: 'Cambridge', year: 2022, quote: "It's a nice way to bring an ethical dimension to May Week, and it's a good cause",
  },
  {
    id: '01G9ZWEBTHHZES68A3F8GC6TJR', name: 'Muhib Ali, Natural Sciences Student @ Trinity Hall', chapter: 'Cambridge', year: 2022, quote: 'Izzy didn’t stop asking 😔😔😔',
  },
  {
    id: '01G9ZWEBTHJJ15YRC7RDP3HBKW', name: 'Liz Samir, Medicine Student @ Christ’s', chapter: 'Cambridge', year: 2022, quote: 'I love the MWA philosophy and it’s really changed the way that I will think about charity going forward. It’s a wonderful community to be a part of and the summer party is a great celebration of the huge collective impact our donations have made!',
  },
  {
    id: '01G9ZWEBTHSVP9R5T0Y88TH98F', name: 'Kishen Joshi, Natural sciences Student @ Trinity hall', chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTMX44914A2J0JDHDN5', name: 'Hasan Nazir, Medicine Student @ Queens', chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTHJEPMKQ9Q56R1ZJW0', name: 'Shruti Biyani, Economics Student @ Magdalene', chapter: 'Cambridge', year: 2022, quote: 'As students we live busy, hectic lives where charity may not be prioritised - MWA gives you the chance to put time aside and make a deliberate contribution as well as connecting you with an incredible community.',
  },
  {
    id: '01G9ZWEBTH6SH3JA3995M27088', name: "Ben Zandonati, Engineering Student @ Christ's", chapter: 'Cambridge', year: 2022, quote: 'MWA does incredible things, and their amazing ethos and energy keeps everyone going!',
  },
  {
    id: '01G9ZWEBTH283H1S5QH5P1BVA4', name: 'Daisy Brown, HSPS Student @ Trinity Hall', chapter: 'Cambridge', year: 2022, quote: 'A chance to give back to charity and do something meaningful!',
  },
  {
    id: '01G9ZWEBTGV1S60VGYY0D4YW5B', name: 'Caroline Baumöhl, Law Student @ Emmanuel', chapter: 'Cambridge', year: 2022, quote: 'I joined MWA because it allows students to make a positive impact and help a lot of people. Moreover, MWA is a great community and the summer party is a lot of fun!',
  },
  {
    id: '01G9ZWEBTG4M730PNMQV8C5R5V', name: 'Rudolf Laine, Computer Science Student @ Trinity', chapter: 'Cambridge', year: 2022, quote: 'Doing good things is good.',
  },
  {
    id: '01G9ZWEBTFTPA0ASKCBJ5P44M3', name: 'Anonymous, Anthropology Student @ Grey College', chapter: 'Durham', year: 2022, quote: 'My friend told me about the society and I thought it was a great cause.',
  },
  {
    id: '01G9ZWEBTMD9WJACFHFYF5PCTH', name: 'Caitlin McCracken, Psychological and Behavioural Sciences Student @ Girton', chapter: 'Cambridge', year: 2022, quote: 'This is an amazing movement and I wanted to challenge myself to give a large sum of money and to think more deliberately about my giving.',
  },
  {
    id: '01G9ZWEBTHZDBD84G05NS7WQDK', name: 'Keely Price, Theology Student @ Sidney Sussex', chapter: 'Cambridge', year: 2022, quote: 'Impact, community, making giving a positive experience',
  },
  {
    id: '01G9ZWEBTHN83WA0B4FZEQHWJE', name: 'Diyana Nikolova, Mathematics Student @ Murray Edwards', chapter: 'Cambridge', year: 2022, quote: 'MWA is a very friendly community and gives me an opportunity to continue doing good throughout uni.',
  },
  {
    id: '01G9ZWEBTF0RPDZHFKX78WMDYP', name: 'Ben Smurthwaite, Philosophy and Theology Student @ Grey College', chapter: 'Durham', year: 2022, quote: 'A great way to help others through your own prospects.',
  },
  {
    id: '01G9ZWEBTH8HTES62FAR3928T9', name: 'Meta Posthumus, Classics Student @ Pembroke', chapter: 'Cambridge', year: 2022, quote: 'Doing little bits to help others whenever we can is absolutely crucial. I believe that if you are able to support others, with even the smallest actions or donations, it is a privileged position to be in and you should take advantage of that. If the impact for you is small, but has a large impact for someone else, offering help should be a no-brainer.',
  },
  {
    id: '01G9ZWEBTGMG07JCJZRQ3HEP4N', name: 'Sylvia Lei, Education Student @ Churchill', chapter: 'Cambridge', year: 2022, quote: "As a very privileged person, I think it's important to give when you can. Sometimes, it can be difficult to choose the right organisation, but I really liked MWA's transparency and philosophy.",
  },
  {
    id: '01G9ZWEBTM8GD609YC72NWMTG4', name: 'Persephone Tsebelis, Computer Science Student @ Lucy Cavendish', chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTMWX8T2FP4B2ERJF1Y', name: 'Felix Elliott, Music Student @ Girton', chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTGW7CBH6C0AGFF4WPS', name: 'Anonymous, HSPS Student @ Hughes Hall', chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTH7Z3KNTFJSW1AS6CF', name: 'Shavindra Jayasekera, Mathematics Student @ Trintiy', chapter: 'Cambridge', year: 2022, quote: 'I love the feel good vibes that MWA brings. So lucky to have joined it in my first year and made some great friends as a result. MWA has really changed my perspective on charity and that is something I will take away with me when I graduate.',
  },
  {
    id: '01G9ZWEBTM56CH55R5JPTDY14T', name: "Benjamin Mulholland, MMLL Student @ Christ's", chapter: 'Cambridge', year: 2022, quote: 'MWA is such a positive movement. It is amazing to devote your time to something that has a really positive tangible impact.',
  },
  {
    id: '01G9ZWEBTHT0Q4RWM22EJAW9KK', name: 'Henry Colbert, Mathematics Student @ Girton', chapter: 'Cambridge', year: 2022, quote: 'I joined last year during the corona lockdowns to meet great new people while also helping make a real difference to the world.',
  },
  {
    id: '01G9ZWEBTMW7EBP1AAJQSW1GD0', name: 'Isabella Gilbey Smith, Biological Natural Sciences Student @ Trinity Hall', chapter: 'Cambridge', year: 2022,
  },
  {
    id: '01G9ZWEBTHCMJWAG9Z8C1WHK2Z', name: 'Mohamed Bushry Basheer, Medicine Student @ Downing', chapter: 'Cambridge', year: 2022, quote: 'MWA allows me to have a good impact, and its philosophy is something I can carry forward throughout my life.',
  },
  {
    id: '01G9ZWEBTMNKC274SS7KNRAC4D', name: 'Clara Tuffrey, Theology Student', chapter: 'Cambridge', year: 2021, quote: "I joined MWA because I was inspired by the philosophy of positive, deliberate giving. The MWA community is really lovely and welcoming, and I've loved being a part of it!", img: '/shared/images/yearbook/01G9ZWEBTMNKC274SS7KNRAC4D.jpg',
  },
  {
    id: '01G9ZWEBTMH06FH1T9Y4B05885', name: 'Jacob Smith, Natural Sciences Student', chapter: 'Cambridge', year: 2021, quote: 'For me, MWA is special because it takes a seemingly simple idea — that giving should be a positive thing — and uses it to have a huge impact. The fact that hundreds of students have made likely the biggest donations of their lives, and will hopefully continue to do in their future lives, is a testament to how powerful this idea is.', img: '/shared/images/yearbook/01G9ZWEBTMH06FH1T9Y4B05885.jpg',
  },
  {
    id: '01G9ZWEBTM8408Q9YXP8KTQ3V4', name: 'Areeg Emarah, Engineering Student', chapter: 'Cambridge', year: 2021, quote: 'MWA to me is about community! I have met some of the most wonderful people over my 4 years from MWA and it’s been such a joy seeing it grow into this beautiful movement!', img: '/shared/images/yearbook/01G9ZWEBTM8408Q9YXP8KTQ3V4.jpg',
  },
  {
    id: '01G9ZWEBTMGDT2T4VZ1QH67YQC', name: 'Lewis Westwood Flood, Human, Social, and Political Sciences Student', chapter: 'Cambridge', year: 2021, quote: 'To contribute positively, and to break away from the incredible insular May Week celebrations.', img: '/shared/images/yearbook/01G9ZWEBTMGDT2T4VZ1QH67YQC.jpg',
  },
  {
    id: '01G9ZWEBTFJ3A25R0GBTF8XQK8', name: 'Adam Abu-Seer, Geography Student', chapter: 'Durham', year: 2021, quote: 'To change my community for the better and encourage others to do so', img: '/shared/images/yearbook/01G9ZWEBTFJ3A25R0GBTF8XQK8.jpg',
  },
  {
    id: '01G9ZWEBTMHRZ5BYDPYY9SGJGG', name: "Seán O'Neill, English Student", chapter: 'Cambridge', year: 2021, quote: 'I wanted to support the alternative versions of giving and May week celebration MWA introduces to Cambridge. I very much hope MWA becomes a staple tradition of many May weeks to come!', img: '/shared/images/yearbook/01G9ZWEBTMHRZ5BYDPYY9SGJGG.jpg',
  },
  {
    id: '01G9ZWEBTMZGRJYHPDJG7AJA1Y', name: 'Rebecca Tyson, Computer Science Student', chapter: 'Cambridge', year: 2021, quote: "MWA is a truly special community of people that together have achieved such great impact. It's so exciting to continue to be a part of!", img: '/shared/images/yearbook/01G9ZWEBTMZGRJYHPDJG7AJA1Y.jpg',
  },
  {
    id: '01G9ZWEBTMTA8NQH4XPAVXXCBH', name: 'Caroline Baumöhl, Law Student', chapter: 'Cambridge', year: 2021, quote: 'I was inspired by the huge positive impact MWA allowed each student to have. I enjoyed being part of such a kind-hearted, open-minded and enthusiastic community.', img: '/shared/images/yearbook/01G9ZWEBTMTA8NQH4XPAVXXCBH.jpg',
  },
  {
    id: '01G9ZWEBTMDB12B2SD747PR2HD', name: 'Lin Bowker-Lonnecker, MET Student', chapter: 'Cambridge', year: 2021, quote: 'So awesome I am still joining as alumni.', img: '/shared/images/yearbook/01G9ZWEBTMDB12B2SD747PR2HD.jpg',
  },
  {
    id: '01G9ZWEBTMJBXFPVQV5WJXQKYY', name: 'James Bridson, Biological Natural Sciences Student', chapter: 'Cambridge', year: 2021, quote: 'Introduced to MWA by a friend, I realised that if I was completely willing to spend so much money on a May Ball ticket - a pretty indulgent affair that brings temporary happiness to one person - I had to reassess my relationship with money, and start thinking about how much more happiness I could bring to so many more people by giving. Joining MWA was a step towards making giving an everyday part of my life, I hope for the rest of my life.', img: '/shared/images/yearbook/01G9ZWEBTMJBXFPVQV5WJXQKYY.jpg',
  },
  {
    id: '01G9ZWEBTMMQ5GWQ3AAEZEZSQT', name: 'Jeremy Schiff, Natural Sciences Student', chapter: 'Cambridge', year: 2021, img: '/shared/images/yearbook/01G9ZWEBTMMQ5GWQ3AAEZEZSQT.jpg',
  },
  {
    id: '01G9ZWEBTMXJ0PTZ9DPK5R78HS', name: 'Sam Kunin, AMES Student', chapter: 'Cambridge', year: 2021, quote: 'Incredible impact, incredible people', img: '/shared/images/yearbook/01G9ZWEBTMXJ0PTZ9DPK5R78HS.jpg',
  },
  {
    id: '01G9ZWEBTM25WM2XNG7D0NM73Z', name: 'Joanna Nowinska, Land Economy Student', chapter: 'Cambridge', year: 2021, quote: 'MWA is an amazing initiative and has definitely been one of the highlights of my time at Cambridge! Being involved is both fun and rewarding and I’d recommend it to anyone.', img: '/shared/images/yearbook/01G9ZWEBTM25WM2XNG7D0NM73Z.jpg',
  },
  {
    id: '01G9ZWEBTMGXFMTGJTGDW54A24', name: 'Adrià Garriga-Alonso, Engineering (PhD) Student', chapter: 'Cambridge', year: 2021, quote: "I used to be opposed to May Balls, because they are very expensive for a single night of partying. I felt quite bad about it after going to one, too. I'm not opposed any more, but I'm very glad that I can give that money to AMF, and still have a fun party!", img: '/shared/images/yearbook/01G9ZWEBTMGXFMTGJTGDW54A24.jpg',
  },
  {
    id: '01G9ZWEBTM2D41NX9KQCNZ8HKR', name: 'Dulan Abeysundara, Medicine Student', chapter: 'Cambridge', year: 2021, quote: 'Great community of people wanting to make a difference through charity.', img: '/shared/images/yearbook/01G9ZWEBTM2D41NX9KQCNZ8HKR.jpg',
  },
  {
    id: '01G9ZWEBTMPJPQRKXZQ13WDMBH', name: 'Connie, Maths Student', chapter: 'Cambridge', year: 2021, quote: 'I joined the MWA because May Week is a time to celebrate and relax: MWA is brilliant, because it combines this with an ability to make a positive impact. It is a community of passionate individuals worth celebrating with, and with whom I can have fun and also make a difference.', img: '/shared/images/yearbook/01G9ZWEBTMPJPQRKXZQ13WDMBH.jpg',
  },
  {
    id: '01G9ZWEBTMHD27AVYEQG4FKG4T', name: 'Sunima Basnet', chapter: 'Cambridge', year: 2021, quote: "Seeing my home country battle with such a brutal disease like Malaria inspired me to join MWA; it gave me a direct platform to make a small contribution towards this fight. After reading more about it, I knew that my donation will be used for the right purposes and for something so much greater such as saving lives and making lasting impact in people's lives.", img: '/shared/images/yearbook/01G9ZWEBTMHD27AVYEQG4FKG4T.jpg',
  },
  {
    id: '01G9ZWEBTMC7Y1F63KG3N6PX21', name: 'George Skeen, History and Politics Student', chapter: 'Cambridge', year: 2021, quote: 'In raising huge amounts of money for charity, MWA has created a wonderful community across Cambridge!', img: '/shared/images/yearbook/01G9ZWEBTMC7Y1F63KG3N6PX21.jpg',
  },
  {
    id: '01G9ZWEBTM5GG0R9PRZT4WGZ13', name: 'Richard Danylyuk, Natural Sciences Student', chapter: 'Cambridge', year: 2021, quote: 'It seemed like the right thing to do!', img: '/shared/images/yearbook/01G9ZWEBTM5GG0R9PRZT4WGZ13.jpg',
  },
  {
    id: '01G9ZWEBTMRVRK7YJ95KZB9445', name: 'Felix Elliott, Music Student', chapter: 'Cambridge', year: 2021, img: '/shared/images/yearbook/01G9ZWEBTMRVRK7YJ95KZB9445.jpg',
  },
  {
    id: '01G9ZWEBTFQD7TE8EHD5NJ9JFM', name: 'Kevin Roice, Physics and Computer Science Student', chapter: 'Durham', year: 2021, img: '/shared/images/yearbook/01G9ZWEBTFQD7TE8EHD5NJ9JFM.jpg',
  },
  {
    id: '01G9ZWEBTMJ9JKC8TC7RHQTH2Q', name: 'Rose Schechter, English Student', chapter: 'Cambridge', year: 2021, quote: 'To connect with people and give to charity!', img: '/shared/images/yearbook/01G9ZWEBTMJ9JKC8TC7RHQTH2Q.jpg',
  },
  {
    id: '01G9ZWEBTM698Q08SZ3G6H7BNT', name: 'Emily Bassalian, Education, Policy and International Development Student', chapter: 'Cambridge', year: 2021, quote: "MWA's community is unbeatable ! Everyone is super friendly, kind and we all have the same goal at heart. I absolutely love the friends that I've made, the contribution that we've had and the events that I have helped to organise and the many others that I have attended.", img: '/shared/images/yearbook/01G9ZWEBTM698Q08SZ3G6H7BNT.jpg',
  },
  {
    id: '01G9ZWEBTMSPJ7GE7Q54YWTDS8', name: 'Alastair Nicol, Politics and International Relations Student', chapter: 'Cambridge', year: 2021, quote: "It's a fun way to make the world a better place :)", img: '/shared/images/yearbook/01G9ZWEBTMSPJ7GE7Q54YWTDS8.jpg',
  },
  {
    id: '01G9ZWEBTFS68MPSMV7T1Z3S43', name: 'Alex Greer, Chemistry Student', chapter: 'Durham', year: 2021, quote: 'I believe students are in an incredible position to improve wellbeing through charitable donations while at university and through our future careers.', img: '/shared/images/yearbook/01G9ZWEBTFS68MPSMV7T1Z3S43.jpg',
  },
  {
    id: '01G9ZWEBTFENJBR5ABZ6JGVYRZ', name: 'Alex Walker, PPE Student', chapter: 'Durham', year: 2021, quote: "Raise is a really exciting and POSITIVE community who share the same values. I'm very glad I got involved this year.", img: '/shared/images/yearbook/01G9ZWEBTFENJBR5ABZ6JGVYRZ.jpg',
  },
  {
    id: '01G9ZWEBTFWZ611Z8JJTQPN43W', name: 'Aoife Walter, History Student', chapter: 'Durham', year: 2021, quote: 'To re-think giving and to meet a group of like-minded, conscientious people in Durham that I would never usually meet.', img: '/shared/images/yearbook/01G9ZWEBTFWZ611Z8JJTQPN43W.jpg',
  },
  {
    id: '01G9ZWEBTF3KMHGZXM0J2014RK', name: 'Adeline Zhao, Philosophy Student', chapter: 'Durham', year: 2021, quote: 'Finding the Fun in Fundraising!', img: '/shared/images/yearbook/01G9ZWEBTF3KMHGZXM0J2014RK.jpg',
  },
  {
    id: '01G9ZWEBTF0W0NZWMBBW1JD951', name: 'Edith Sandulescu, Ba Criminology Student', chapter: 'Durham', year: 2021, quote: 'I really enjoy helping people and I also thought this would be an amazing opportunity to make new friends.', img: '/shared/images/yearbook/01G9ZWEBTF0W0NZWMBBW1JD951.jpg',
  },
  {
    id: '01G9ZWEBTMBQDK9C8VZWENDEHB', name: 'Jonah Gibbon, Mathematics Student', chapter: 'Cambridge', year: 2021, quote: 'My friends told me about it, but ultimately it’s the good work the charity does', img: '/shared/images/yearbook/01G9ZWEBTMBQDK9C8VZWENDEHB.jpg',
  },
  {
    id: '01G9ZWEBTMNPCBABQXMS1X27C6', name: 'Emma Rowley, Linguistics Student', chapter: 'Cambridge', year: 2021, quote: 'I decided to join MWA for its positive ethos and sense of community', img: '/shared/images/yearbook/01G9ZWEBTMNPCBABQXMS1X27C6.jpg',
  },
  {
    id: '01G9ZWEBTF9DRS5SMMP7PVWWAJ', name: 'Harry, History Student', chapter: 'Durham', year: 2021, quote: 'I decided to join Raise to learn more about how fundraising is structured and gain some valuable skills along the way. Helping to raise over £25,000 has been an exceptionally rewarding experience.', img: '/shared/images/yearbook/01G9ZWEBTF9DRS5SMMP7PVWWAJ.jpg',
  },
  {
    id: '01G9ZWEBTMDCQ3RTS4C1E4NY42', name: 'Rachel Ezekiel, Natural Sciences Student', chapter: 'Cambridge', year: 2021, img: '/shared/images/yearbook/01G9ZWEBTMDCQ3RTS4C1E4NY42.jpg',
  },
  {
    id: '01G9ZWEBTMF95GJ6ZT7KZH4DKS', name: 'Laurens Smulders, Natural Sciences Student', chapter: 'Cambridge', year: 2021, quote: 'I realise how privileged I am being a Cambridge student and how not everyone gets this opportunity. It felt amazing giving back by donating to AMF.', img: '/shared/images/yearbook/01G9ZWEBTMF95GJ6ZT7KZH4DKS.jpg',
  },
  {
    id: '01G9ZWEBTM3SD98GBHK836WRJE', name: 'Jake Mendel, Theoretical Physics Student', chapter: 'Cambridge', year: 2021, quote: 'Georgie is a relentless man. Had a great time each year kept coming back for more', img: '/shared/images/yearbook/01G9ZWEBTM3SD98GBHK836WRJE.jpg',
  },
  {
    id: '01G9ZWEBTF5M6K3B3093YQ380Z', name: 'Charlie Warburton, Economics Student', chapter: 'Durham', year: 2021, quote: 'To give to charity in a more engaged way', img: '/shared/images/yearbook/01G9ZWEBTF5M6K3B3093YQ380Z.jpg',
  },
  {
    id: '01G9ZWEBTM99EGTGYA5Q5ECF9Y', name: 'Henry Colbert, Mathematics Student', chapter: 'Cambridge', year: 2021, quote: 'I joined MWA to help spread its Feel Good Do Good philosophy and to make a positive impact to the world in such rough times. The MWA community has been my highlight of this covid affected year.', img: '/shared/images/yearbook/01G9ZWEBTM99EGTGYA5Q5ECF9Y.jpg',
  },
  {
    id: '01G9ZWEBTMNEXTV4FTY5JD961M', name: 'Karyna, Mathematics Student', chapter: 'Cambridge', year: 2021, quote: 'MWA has a unique approach to giving that inspires people to donate for a good cause.', img: '/shared/images/yearbook/01G9ZWEBTMNEXTV4FTY5JD961M.jpg',
  },
  {
    id: '01G9ZWEBTMYX7CJHX3X64HS6B8', name: 'Florine Rombach, Physics Student', chapter: 'Oxford', year: 2021, quote: 'We all have the power to affect and improve the world around us - Raise helped me realized the impact I can make!', img: '/shared/images/yearbook/01G9ZWEBTMYX7CJHX3X64HS6B8.jpg',
  },
  {
    id: '01G9ZWEBTFXWMCPMC3BYAV8PZZ', name: 'Diana Ionita, BSc Psychology Student', chapter: 'Durham', year: 2021, quote: 'I thought it was a great and unique initiative and I wasn’t wrong at all! I enjoyed every minute of it and I’m happy that we made a difference in the society by helping others!', img: '/shared/images/yearbook/01G9ZWEBTFXWMCPMC3BYAV8PZZ.jpg',
  },
  {
    id: '01G9ZWEBTMKPKNWXFZSNFRCD82', name: 'Diyana Nikolova, Mathematics Student', chapter: 'Cambridge', year: 2021, quote: 'I love charity work and the MWA community is so friendly, it was a very easy yes!', img: '/shared/images/yearbook/01G9ZWEBTMKPKNWXFZSNFRCD82.jpg',
  },
  {
    id: '01G9ZWEBTMNSAAVBDY2KCDQEJE', name: 'Abe Tolley, Medicine Student', chapter: 'Cambridge', year: 2021, quote: "I've constantly been inspired to work with the incredible MWA community and see the huge impact we've been able to have together through the power of the simple idea that deliberate giving is worth celebrating!", img: '/shared/images/yearbook/01G9ZWEBTMNSAAVBDY2KCDQEJE.jpg',
  },
  {
    id: '01G9ZWEBTFKZ8KN1N0D2R1PC5P', name: 'Joshua maurice, Geography Student', chapter: 'Durham', year: 2021, quote: 'Having seen the impact MWA had in Cambridge, I was excited to do my part in helping Durham achieve the same!', img: '/shared/images/yearbook/01G9ZWEBTFKZ8KN1N0D2R1PC5P.jpg',
  },
  {
    id: '01G9ZWEBTMS389TAFM0KRJMWDR', name: 'Conor Doherty, Maths Student', chapter: 'Cambridge', year: 2021, quote: 'Helping people is cool.', img: '/shared/images/yearbook/01G9ZWEBTMS389TAFM0KRJMWDR.jpg',
  },
  {
    id: '01G9ZWEBTM2MREAH0MK29DS0HV', name: 'Abby Pope, Law Student', chapter: 'Cambridge', year: 2021, quote: 'I love how MWA focuses on the positive aspect of giving and combines charity with community.', img: '/shared/images/yearbook/01G9ZWEBTM2MREAH0MK29DS0HV.jpg',
  },
  {
    id: '01G9ZWEBTMGP4V8PG4BKD2GCSW', name: 'Isabella Despositos, Geography Student', chapter: 'Cambridge', year: 2021, quote: 'MWA seems a great organisation where I know my donations will make a big difference.', img: '/shared/images/yearbook/01G9ZWEBTMGP4V8PG4BKD2GCSW.jpg',
  },
  {
    id: '01G9ZWEBTF65MFX62FKERJZ731', name: 'Emma Whiley, Liberal Arts Student', chapter: 'Durham', year: 2021, quote: 'I joined Raise to meet a like-minded community of people, who genuinely wanted to change how Durham viewed charitable giving.', img: '/shared/images/yearbook/01G9ZWEBTF65MFX62FKERJZ731.jpg',
  },
  {
    id: '01G9ZWEBTM48JK67Y7Q8RDCDRN', name: 'Toby Stinson, English Student', chapter: 'Cambridge', year: 2021, quote: 'I joined MWA because of the chance it offers to have a huge positive impact and change the way students think about charity. (Plus Clara said I should)', img: '/shared/images/yearbook/01G9ZWEBTM48JK67Y7Q8RDCDRN.jpg',
  },
  {
    id: '01G9ZWEBTM1FH8ZYWRYN2RHF8B', name: 'Shruti biyani, Economics Student', chapter: 'Cambridge', year: 2021, quote: 'Having the chance to make a tangible change and become part of such a tight-knit, caring community was my main motivation.', img: '/shared/images/yearbook/01G9ZWEBTM1FH8ZYWRYN2RHF8B.jpg',
  },
  {
    id: '01G9ZWEBTME7SGW8NBPYNG9FMK', name: 'Gemma Penson, Computer Science Student', chapter: 'Cambridge', year: 2021, quote: "MWA isn't possible without the people and I'm so glad to have been a part of this incredible movement for change!", img: '/shared/images/yearbook/01G9ZWEBTME7SGW8NBPYNG9FMK.jpg',
  },
  {
    id: '01G9ZWEBTMP83XBS1VNA3TJYY7', name: 'Dan Townsend, Mathematics Student', chapter: 'Cambridge', year: 2021, quote: 'In the hope that these donations will be an effective way to save lives.', img: '/shared/images/yearbook/01G9ZWEBTMP83XBS1VNA3TJYY7.jpg',
  },
  {
    id: '01G9ZWEBTMTGJBR86K5ZAEBFM6', name: 'Reef Ronel, Medicine Student', chapter: 'Oxford', year: 2021, quote: 'I wanted to be part of a brilliant community that puts giving at the heart of celebration', img: '/shared/images/yearbook/01G9ZWEBTMTGJBR86K5ZAEBFM6.jpg',
  },
  {
    id: '01G9ZWEBTMF38T1QZ1369WR7AA', name: 'Madeleine Mitchell, Medicine Student', chapter: 'Cambridge', year: 2021, quote: "I decided to join MWA to think more about the way I give to charity, so that it was a deliberate action, as opposed to an afterthought. Being involved in MWA has made me appreciate the effect collective action can have and I've really enjoyed working with other people to achieve our goals.", img: '/shared/images/yearbook/01G9ZWEBTMF38T1QZ1369WR7AA.jpg',
  },
  {
    id: '01G9ZWEBTMPEBS2TPS3ET366T6', name: 'Aura Schonfeld, Human Sciences Student', chapter: 'Oxford', year: 2021, quote: 'Being able to have a huge tangible impact on improving lives across the globe before even entering the workplace seemed almost too good to be true. But Raise offered that and so much more - the community feeling is quite magnificent.', img: '/shared/images/yearbook/01G9ZWEBTMPEBS2TPS3ET366T6.jpg',
  },
  {
    id: '01G9ZWEBTMV1J7CKHREWB81PBT', name: 'Rahul Shah, Medicine Student', chapter: 'Cambridge', year: 2021, quote: 'I joined MWA because I wanted to add more meaning to my time at university through contributing to fantastic causes; MWA has made this not only possible but immensely enjoyable as well!', img: '/shared/images/yearbook/01G9ZWEBTMV1J7CKHREWB81PBT.jpg',
  },
  {
    id: '01G9ZWEBTFS4F4XRMDHSX5NB9M', name: 'Luke Johannes Stuart, Computer Science Student', chapter: 'Durham', year: 2021, quote: 'To help shape positive attitudes to charitable giving and make a positive impact.', img: '/shared/images/yearbook/01G9ZWEBTFS4F4XRMDHSX5NB9M.jpg',
  },
  {
    id: '01G9ZWEBTMX2ZD8FAH3JW65241', name: 'Julian Wreford, Computer Science Student', chapter: 'Cambridge', year: 2021, quote: "It's a great organisation and I love the opportunity to be involved with so many others also donating!", img: '/shared/images/yearbook/01G9ZWEBTMX2ZD8FAH3JW65241.jpg',
  },
  {
    id: '01G9ZWEBTMMYVHC17EAAHY1YGT', name: 'Georgia Baird, History of Art Student', chapter: 'Cambridge', year: 2021, quote: 'I want to make a difference, especially in these hard times!', img: '/shared/images/yearbook/01G9ZWEBTMMYVHC17EAAHY1YGT.jpg',
  },
  {
    id: '01G9ZWEBTFT1Q9JY3QRRAACGEZ', name: 'Ekaterina Kosheleva, Theology and Religion Student', chapter: 'Durham', year: 2021, quote: 'I wanted to be part of the wider student community and during the pandemic this was the biggest project taking place. Additionally, I wanted to help those suffering from Malaria.', img: '/shared/images/yearbook/01G9ZWEBTFT1Q9JY3QRRAACGEZ.jpg',
  },
  {
    id: '01G9ZWEBTMYZR7S6M2K2BS2087', name: 'Rohan Shah, Economics Student', chapter: 'Cambridge', year: 2021, quote: 'I felt that MWA was a fantastic initiative to support, increasing awareness of key issues in society and creating a meaningful positive impact.', img: '/shared/images/yearbook/01G9ZWEBTMYZR7S6M2K2BS2087.jpg',
  },
  {
    id: '01G9ZWEBTM479S5HATQ9M9G0NX', name: 'Georgia Brown, History and Politics Student', chapter: 'Cambridge', year: 2021, quote: 'I loved the philosophy of positive giving, and the community seemed amazing. I was not proved wrong!', img: '/shared/images/yearbook/01G9ZWEBTM479S5HATQ9M9G0NX.jpg',
  },
  {
    id: '01G9ZWEBTMGZFH02HJMT4SFTHE', name: 'Shavindra Jayasekera, Marhematics Student', chapter: 'Cambridge', year: 2021, quote: "I love MWA's feel good, do good ethos. It has definitely changed the way in which I look at giving and I hope it is something I will take into life after uni.", img: '/shared/images/yearbook/01G9ZWEBTMGZFH02HJMT4SFTHE.jpg',
  },
  {
    id: '01G9ZWEBTM4CN45SF20VZ7KNC7', name: 'Sylvie Hodes, AMES Student', chapter: 'Cambridge', year: 2021, quote: 'MWA is one of the most welcoming, positive communities in Cambridge, bringing together an ever-growing group of social-minded students who are doing (and will continue to do!) a whole lotta good in this world!', img: '/shared/images/yearbook/01G9ZWEBTM4CN45SF20VZ7KNC7.jpg',
  },
  {
    id: '01G9ZWEBTM634QMTB7HTRCD3ES', name: 'Rosie Cates', chapter: 'Cambridge', year: 2021, quote: "MWA is definitely a highlight of my time at university. It's a fantastic community and I love watching it flourish year on year!", img: '/shared/images/yearbook/01G9ZWEBTM634QMTB7HTRCD3ES.jpg',
  },
  {
    id: '01G9ZWEBTMND5BS1DHXQ58442A', name: 'Josh Attwell, Maths and Philosophy Student', chapter: 'Oxford', year: 2021, quote: 'I love that Raise encourages students to think about giving to charity, particularly in a way that is so impactful!', img: '/shared/images/yearbook/01G9ZWEBTMND5BS1DHXQ58442A.jpg',
  },
  {
    id: '01G9ZWEBTMYDFWFJFNEKTM9Z25', name: 'Zarya Oh, HSPS Student', chapter: 'Cambridge', year: 2021, quote: 'The MWA philosophy of positive giving is what first drew me to the society, but I gained so much more in terms of opportunities, learning great skills and being part of a super warm and dedicated community of people :)', img: '/shared/images/yearbook/01G9ZWEBTMYDFWFJFNEKTM9Z25.jpg',
  },
  {
    id: '01G9ZWEBTF8FNESYW4AVGAHDW2', name: 'Susanne, Economics Student', chapter: 'Durham', year: 2021, quote: 'I love how Raise challenges us to think about our perception of charity, and encourages a really positive approach towards giving. Being part of the initiative this year was incredibly rewarding!', img: '/shared/images/yearbook/01G9ZWEBTF8FNESYW4AVGAHDW2.jpg',
  },
  {
    id: '01G9ZWEBTM27Y3ZZ8DNM2HNAKP', name: 'Sarah Adegbite, Theology, Religion, and Philosophy of Religion Student', chapter: 'Cambridge', year: 2021, quote: 'I wanted to make a difference with my money and help people in need! It’s easily to feel like there’s not much we can do but we do have the ability to make a change where we are.', img: '/shared/images/yearbook/01G9ZWEBTM27Y3ZZ8DNM2HNAKP.jpg',
  },
  {
    id: '01G9ZWEBTMNW9A3C5FK14Z0YR5', name: 'Benjamin Mulholland, MML Spanish and Portuguese Student', chapter: 'Cambridge', year: 2021, quote: "I wanted to do something really worthwhile, to make a real difference to other people's lives. Being involved in MWA has been inspiring, to see how much we have achieved collectively.", img: '/shared/images/yearbook/01G9ZWEBTMNW9A3C5FK14Z0YR5.jpg',
  },
  {
    id: '01G9ZWEBTMM16SHQC4C9P78FN2', name: 'Holly Richards, English Student', chapter: 'Cambridge', year: 2021, quote: 'I Joined MWA because I wanted to be part of something that adds real value to our community here at Cambridge, and also directly help to make a positive difference in the world! It was also an amazing way to meet lots of lovely new people, especially during a time when it was so hard to do that.', img: '/shared/images/yearbook/01G9ZWEBTMM16SHQC4C9P78FN2.jpg',
  },
  {
    id: '01G9ZWEBTM8QPVP04HRPZRBBVE', name: 'Euan Ong, Computer Science Student', chapter: 'Cambridge', year: 2021, img: '/shared/images/yearbook/01G9ZWEBTM8QPVP04HRPZRBBVE.jpg',
  },
  {
    id: '01G9ZWEBTFA4PKTHFNVPVQ6QZW', name: 'Oscar Duffy, History Student', chapter: 'Durham', year: 2021, quote: 'To donate to an excellent charity while meeting like minded people', img: '/shared/images/yearbook/01G9ZWEBTFA4PKTHFNVPVQ6QZW.jpg',
  },
  {
    id: '01G9ZWEBTMK6CJQX0WAP1W0B2G', name: 'Kristin Rooney, Modern and Medieval Languages Student', chapter: 'Cambridge', year: 2021, quote: 'To get involved with a movement that celebrates deliberate, positive giving!', img: '/shared/images/yearbook/01G9ZWEBTMK6CJQX0WAP1W0B2G.jpg',
  },
  {
    id: '01G9ZWEBTM7086FM6V66EADD56', name: 'Pippa Prendergast-Coates, English Student', chapter: 'Cambridge', year: 2021, img: '/shared/images/yearbook/01G9ZWEBTM7086FM6V66EADD56.jpg',
  },
  {
    id: '01G9ZWEBTM1PXJ3CTBZPXVTTY0', name: 'Alastair Nicol, Politics and International Relations Student', chapter: 'Cambridge', year: 2021, quote: "I joined MWA because it looked like a fun opportunity to improve people's lives and make the world a better place.", img: '/shared/images/yearbook/01G9ZWEBTM1PXJ3CTBZPXVTTY0.jpg',
  },
  {
    id: '01G9ZWEBTM6NZY3G6315PN5VPG', name: 'Chloe Sullivan, Natural Science Student', chapter: 'Cambridge', year: 2021, quote: 'I joined MWA becuase I think it’s a great oppertunity to give to have fun and make friends while doing out bit by giving to charity!', img: '/shared/images/yearbook/01G9ZWEBTM6NZY3G6315PN5VPG.jpg',
  },
  {
    id: '01G9ZWEBTFTA3CRE99MW6HFTJ3', name: 'Oscar Duffy, History Student', chapter: 'Durham', year: 2021, quote: 'To donate to an excellent charity while meeting like minded people', img: '/shared/images/yearbook/01G9ZWEBTFTA3CRE99MW6HFTJ3.jpg',
  },
  {
    id: '01G9ZWEBTMEZ0BW9FQAME4YV7Z', name: 'Maya Smolkova, Medicine Student', chapter: 'Cambridge', year: 2021, quote: 'I really wanted to give back now that I am finally in a position to do so!', img: '/shared/images/yearbook/01G9ZWEBTMEZ0BW9FQAME4YV7Z.jpg',
  },
  {
    id: '01G9ZWEBTMDGXEYXCHTE3DSXC1', name: 'Emily Hudson, Physics Student', chapter: 'Oxford', year: 2021, quote: 'Raise is great for effecting real change! I really like the philosophy of donating money that has some significance to you.', img: '/shared/images/yearbook/01G9ZWEBTMDGXEYXCHTE3DSXC1.jpg',
  },
  {
    id: '01G9ZWEBTFCX9N7PP41QAWKQYW', name: 'Jacob Smith, Natural Sciences Student', chapter: 'Durham', year: 2021, quote: 'For me, MWA is special because it takes a seemingly simple idea — that giving should be a positive thing — and uses it to have a huge impact. The fact that hundreds of students have made likely the biggest donations of their lives, and will hopefully continue to do in their future lives, is a testament to how powerful this idea is.', img: '/shared/images/yearbook/01G9ZWEBTFCX9N7PP41QAWKQYW.jpg',
  },
  {
    id: '01G9ZWEBTMT38VRFHV93WXB11N', name: 'Eloise Holland, Mathematics and Computer Science Student', chapter: 'Oxford', year: 2021, quote: 'I joined raise because I love how it celebrates giving and the donations go to a really great and effective cause.', img: '/shared/images/yearbook/01G9ZWEBTMT38VRFHV93WXB11N.jpg',
  },
  {
    id: '01G9ZWEBTFYH8955PNNY9GZBMF', name: 'Anna Hubbard, Biological Sciences Student', chapter: 'Durham', year: 2021, img: '/shared/images/yearbook/01G9ZWEBTFYH8955PNNY9GZBMF.jpg',
  },
  {
    id: '01G9ZWEBTMGTVFGNCJBPB260JA', name: 'Jacob Arbeid, HML Student', chapter: 'Cambridge', year: 2021, quote: "I've always felt that the amazing opportunities we have to improve the lives of people around the world should be celebrated. It's been amazing to see that idea grow in Cambridge over the last few years with MWA - and with AMF, you know it's going to an effective cause!", img: '/shared/images/yearbook/01G9ZWEBTMGTVFGNCJBPB260JA.jpg',
  },
  {
    id: '01G9ZWEBTFQ99Q1184FT730YAP', name: 'Olivia Buckley, Psychology Student', chapter: 'Durham', year: 2021, quote: 'I joined Raise because it was an exciting, innovative, and accessible way to incorporate giving into student life. Thank you for introducing me to this great initiative!', img: '/shared/images/yearbook/01G9ZWEBTFQ99Q1184FT730YAP.jpg',
  },
  {
    id: '01G9ZWEBTM73TXQVG1FNYAP3WQ', name: 'Arthur Conmy, Mathematics Student', chapter: 'Cambridge', year: 2021, quote: 'To make the large impact of high impact charity *feel* wonderful.', img: '/shared/images/yearbook/01G9ZWEBTM73TXQVG1FNYAP3WQ.jpg',
  },
  {
    id: '01G9ZWEBTFEN26SM6PGGSZYQ0J', name: 'Sonny, Finance Student', chapter: 'Durham', year: 2021, quote: 'I joined raise not to only make a difference, but to make a difference that inspired a continuous change in the way people think about giving. I fully support the raise philosophy that giving should be a celebrated experience of the impact, rather than just a single instance of doing a good deed.', img: '/shared/images/yearbook/01G9ZWEBTFEN26SM6PGGSZYQ0J.jpg',
  },
  {
    id: '01G9ZWEBTFQPC6CDMCRKT8S2QM', name: 'Natasha Skaife, Criminology Student', chapter: 'Durham', year: 2021, quote: 'It was great to see the ideals around charity changed and it felt great to be a part of something so giving', img: '/shared/images/yearbook/01G9ZWEBTFQPC6CDMCRKT8S2QM.jpg',
  },
  {
    id: '01G9ZWEBTM67X3ZHAX2Z8DQQ67', name: 'Felix Haynes, HSPS Student', chapter: 'Cambridge', year: 2021, quote: 'I wanted to see the direct impact of my donation, and MWA let me do that while also joining a community of students passionate about giving.', img: '/shared/images/yearbook/01G9ZWEBTM67X3ZHAX2Z8DQQ67.jpg',
  },
  {
    id: '01G9ZWEBTM17KDEQEVJZTYPW2H', name: 'Noam Solomons-Wise, Music Student', chapter: 'Cambridge', year: 2021, quote: 'It is a great opportunity to joyfully give to charity and it has inspired me to be more active in my giving.', img: '/shared/images/yearbook/01G9ZWEBTM17KDEQEVJZTYPW2H.jpg',
  },
  {
    id: '01G9ZWEBTFXCE3Q5C7E1699WG3', name: 'Chloe Allen, Law Student', chapter: 'Durham', year: 2021, quote: 'The philosophy of Raise attracted me from the get-go. Celebrating achievements in our own lives by effectively giving to others seemed (and has proved to be) incredibly rewarding. This is an attitude I will continue in later life.', img: '/shared/images/yearbook/01G9ZWEBTFXCE3Q5C7E1699WG3.jpg',
  },
  {
    id: '01G9ZWEBTMY83BH5E5PG1FGTT9', name: 'Imogen Perkins, Medicine Student', chapter: 'Cambridge', year: 2021, quote: 'I feel proud to be part of such an incredible community, that is taking action against a disease that is sadly still very prevalent. MWA is a great way to get involved in making our world a safer and better place!', img: '/shared/images/yearbook/01G9ZWEBTMY83BH5E5PG1FGTT9.jpg',
  },
  {
    id: '01G9ZWEBTM65HXNRXSJ5FSC14H', name: 'Rob Maclennan, Economics Student', chapter: 'Cambridge', year: 2021, quote: "I joined MWA because I believe that giving should be something that we celebrate rather than stigmatise! It's so great to be part of a community that makes such a positive collective impact while changing the narrative around giving for the better.", img: '/shared/images/yearbook/01G9ZWEBTM65HXNRXSJ5FSC14H.jpg',
  },
  {
    id: '01G9ZWEBTMPJHRPJA398E1952V', name: 'Gabriel Sibthorp-Quarmby, Law Student', chapter: 'Cambridge', year: 2021, quote: 'A friend on the committee explained what they did, and the impacts of it and the philosophy, and it all sounded like a really positive way to change the world, at least a little.', img: '/shared/images/yearbook/01G9ZWEBTMPJHRPJA398E1952V.jpg',
  },
  {
    id: '01G9ZWEBTMW1N0E4Q863NC95HS', name: 'Mithylan Ganeshwaran, Medicine Student', chapter: 'Cambridge', year: 2021, quote: 'I think that MWA promotes a really powerful philosophy, i.e. that you can celebrate while giving to hugely deserving causes at the same time!', img: '/shared/images/yearbook/01G9ZWEBTMW1N0E4Q863NC95HS.jpg',
  },
  {
    id: '01G9ZWEBTF46J87AG8E20RA2EH', name: 'Clarissa Eugenia Henderi, Law Student', chapter: 'Durham', year: 2021, quote: "Raise's wholehearted effort to give others a brighter future makes for a humbling and meaningful initiative that I'm proud to be part of, and is one that has inspired me very much.", img: '/shared/images/yearbook/01G9ZWEBTF46J87AG8E20RA2EH.jpg',
  },
  {
    id: '01G9ZWEBTM6KFBFEE09ZRXEH3F', name: 'Ella Shindler, English Student', chapter: 'Cambridge', year: 2021, quote: 'Being given the opportunity to make an actually difference working together with other students .',
  },
  {
    id: '01G9ZWEBTGQKKXRNA48NSR97YE', name: 'Lucia Harrington', chapter: 'Glasgow', year: 2021, quote: 'I joined Raise because I believed in the philosophy of the movement . I agreed that by giving significant donations we would be able to support charities that make a real impact in a very effective way.',
  },
  {
    id: '01G9ZWEBTFNGTPKKY7R6X194SJ', name: 'Anonymous, Medicine Student', chapter: 'Glasgow', year: 2021, quote: "Giving a larger donation like this means I'll be missing out on things I want myself, I'm actually thinking about where my money is going and the impact it has.",
  },
  {
    id: '01G9ZWEBTG4X3MW98QXEAKHEGT', name: 'Kate Murray', chapter: 'Glasgow', year: 2021, quote: 'The focus on “celebrating giving” was unique and I wanted the opportunity to be part of something that achieved this while making a huge impact. The challenge of starting a charitable society during COVID was very exciting.',
  },
  {
    id: '01G9ZWEBTGZBBP73907QTBN8S6', name: 'Ameerah, Ameerah Student', chapter: 'Glasgow', year: 2021, quote: "I wanted to get involved with charity work despite the pandemic and Raise seemed like not only a good way to do it, but a chance to meet new people! The AMF is such a great charity to support too - in this day and age people shouldn't be dying of preventable disease",
  },
  {
    id: '01G9ZWEBTM99CSP8FVWJWM9206', name: 'Varun Muralidharan, Natural Sciences Student', chapter: 'Cambridge', year: 2021, quote: 'I joined MWA because of its positive message of deliberate giving. By coming together as one amazing community, we can have a large tangible impact.',
  },
  {
    id: '01G9ZWEBTGGPP920CMW6XFSE3K', name: 'Andrew Taylor, Microbiology Student', chapter: 'Glasgow', year: 2021, quote: 'I joined Raise because of huge impact we can have while having a great time. A donation equivalent to a round of 5 pints of fun can protect 63 people from malaria which is just amazing.',
  },
  {
    id: '01G9ZWEBTMR0X7DHSMH7WRXP9R', name: 'Jonathan Hoare', chapter: 'Cambridge', year: 2021,
  },
  {
    id: '01G9ZWEBTGW81E1T7XBKRWW5BY', name: 'Scott Blair, Pharmacology Student', chapter: 'Glasgow', year: 2021, quote: 'I decided to get involved with Raise this year as it was a new society with such an important message that students can come together and make a huge impact on so many lives.',
  },
  {
    id: '01G9ZWEBTMNP1P983M7MTYG5K6', name: 'Jack Lubner, History Student', chapter: 'Cambridge', year: 2021,
  },
  {
    id: '01G9ZWEBTGD66K9CNTGRKQ38VT', name: 'Shona, Neuroscience Student', chapter: 'Glasgow', year: 2021, quote: 'I joined Raise to get to know like-minded students who shared the same vision about making a positive impact in our community by changing the way people think about giving. Raise has been a great opportunity to meet new people in a year where socialising has been so difficult, while doing good and feeling good at the same time.',
  },
  {
    id: '01G9ZWEBTMNR4ZBGASZT1R75P9', name: 'Lara Hull, PPE Student', chapter: 'Oxford', year: 2021,
  },
  {
    id: '01G9ZWEBTF5YSD3MM6G3JFYCWV', name: 'Eryka Kobelczuk, Law Student', chapter: 'Glasgow', year: 2021, quote: 'I decided to join Raise to help spread the message of helping others around us and the world. It is so important that we all make it our responsibility to do good and help those who need it, whether that be by charity work, volunteering or donating, as long as you are making a change.',
  },
  {
    id: '01G9ZWEBTFC6FZTHRA26X5MNP1', name: 'Billy, History Student', chapter: 'Durham', year: 2021, quote: 'I loved their message of rethinking the philosophy behind student attitudes to charity. It’s time to put it at the centre of everything we do',
  },
  {
    id: '01G9ZWEBTGRAKY9F5WH7CPDMGC', name: 'alex odonnell, business and psychology Student', chapter: 'Glasgow', year: 2021, quote: 'Meeting new people and donating',
  },
  {
    id: '01G9ZWEBTG5G4892NRZHPHWK9Z', name: 'Maggie English, Geography & Politics Student', chapter: 'Glasgow', year: 2021, quote: 'Refreshing and highly impactful alternative to traditional fundraising.',
  },
  {
    id: '01G9ZWEBTF6EQKGJB0E8RWB3B5', name: 'Maisie Proctor, History Student', chapter: 'Durham', year: 2021,
  },
  {
    id: '01G9ZWEBTGNN5WET0Y4SJQYTJ3', name: 'Rhiannon Fagan, Scots Law Student', chapter: 'Glasgow', year: 2021, quote: 'I got involved with Raise this year because i love the positivity of this community; seeing everyone come together to make a significant impact, was a genuinely new outlook on charity for me which i felt i needed to get involved with.',
  },
  {
    id: '01G9ZWEBTGMP6TDV23NEB6X50Y', name: 'Chloe Trott, Sociology and Public Policy Student', chapter: 'Glasgow', year: 2021, quote: 'I loved the idea that this movement could not only help the Against Malaria Foundation but also change the mindset of students, doubling the long term impact. I also thought it was the perfect way to meet lots of likeminded people, working together to do something amazing!',
  },
  {
    id: '01G9ZWEBTMA61WTTJNKACSV9DJ', name: 'James saker, Maths Student', chapter: 'Cambridge', year: 2021, quote: 'College dad told me about it, has been great fun',
  },
  {
    id: '01G9ZWEBTM6RBTQDHWH1PB7FB2', name: 'Emily Barker, Maths Student', chapter: 'Cambridge', year: 2021, quote: 'I love the idea of being part of a community of like-minded people, working towards a common goal for positive change in the world. Joining MWA has provided all that and more!',
  },
  {
    id: '01G9ZWEBTM37X7FFTC26AKEZJ9', name: 'Dhruv Sharma, Medicine Student', chapter: 'Cambridge', year: 2021,
  },
  {
    id: '01G9ZWEBTF0WDGXAZ33CWK93K6', name: 'Anonymous, Neuroscience Student', chapter: 'Glasgow', year: 2021, quote: 'Great foundation, great group of people and from joining Raise my perspective of donating has changed for the better. I can’t wait to see what the next year holds, hopefully some more in person events.',
  },
  {
    id: '01G9ZWEBTGWR1HWTBW6C1M2TQ3', name: 'Hamish Rae, Pharmacology Student', chapter: 'Glasgow', year: 2021, quote: 'I loved the idea of changing the way students think about giving. Also I lived with Andrew.',
  },
  {
    id: '01G9ZWEBTGC3BQBJRBKZQRKGQP', name: 'Molly McLaughlin, Law LLB Student', chapter: 'Glasgow', year: 2021, quote: 'I was attracted to Raise’s unique way of raising money and thought it was an innovative way of getting people to donate',
  },
  {
    id: '01G9ZWEBTMDTWQ80PF8QQ28HC0', name: 'Anonymous, Engineering Student', chapter: 'Cambridge', year: 2021,
  },
  {
    id: '01G9ZWEBTM0VG73FD05MRQHFMK', name: 'Katy Ratcliffe, PBS Student', chapter: 'Cambridge', year: 2021,
  },
  {
    id: '01G9ZWEBTMPERNPWG9GPT4QKW5', name: 'Anonymous, Economics Student', chapter: 'Cambridge', year: 2021,
  },
  {
    id: '01G9ZWEBTFJYYMN57GDQ8CMEAS', name: 'Anonymous, PPE Student', chapter: 'Durham', year: 2021, quote: 'Great way to raise money.',
  },
  {
    id: '01G9ZWEBTGDQ2ZBY4GCFKT2E8P', name: 'Sharath Nambiar, Common Law and Politics Student', chapter: 'Glasgow', year: 2021, quote: "Raise showed me how I can both be charitable and also celebrate that giving and collective change in the process. I couldn't be more happier of my involvement in Raise :))",
  },
  {
    id: '01G9ZWEBTGWPAWZRPABYQ7N6VV', name: 'Laiba Amjad, International relations, economic and social history Student', chapter: 'Glasgow', year: 2021, quote: 'I decided to join raise as a way to make a small but meaningful contribution.',
  },
  {
    id: '01G9ZWEBTFGATVBJSDVDH9RZ4A', name: 'Anonymous', chapter: 'Glasgow', year: 2021, quote: "It's a great initiative that helps positively shift the mindset of the students getting involved, all while benefiting an important cause.",
  },
  {
    id: '01G9ZWEBTMBJ9F4FVXAB28YEQH', name: 'Anonymous, Modern Languages Student', chapter: 'Oxford', year: 2021,
  },
  {
    id: '01G9ZWEBTF04YVNCQAZTE7XHC8', name: 'Anonymous, Law Student', chapter: 'Glasgow', year: 2021,
  },
  {
    id: '01G9ZWEBTMTH037R9FFZ9CVS20', name: 'Anonymous, Mathematics Student', chapter: 'Cambridge', year: 2021,
  },
  {
    id: '01G9ZWEBTGGA70FVQYCA3AGFAB', name: 'Ioana Barna, Genetics Student', chapter: 'Glasgow', year: 2021, quote: 'I loved the positive philosophy it brought to charity!',
  },
  {
    id: '01G9ZWEBTF9J3MMNKZ21TNPGQD', name: 'Meg Pitts, Psychology Student', chapter: 'Glasgow', year: 2021, quote: 'I heard about Raise through a friend in the committee and thought it was an good idea. I like the focus on choosing the most effective charities and thought the matched funding made all donations really worthwhile',
  },
  {
    id: '01G9ZWEBTMW343086T7YZE5XPG', name: 'Agnijo Banerjee, Mathematics Student', chapter: 'Cambridge', year: 2021,
  },
  {
    id: '01G9ZWEBTMF9A66H2Y2QKTH7SN', name: 'Anonymous, Land Economy Student', chapter: 'Cambridge', year: 2021,
  },
  {
    id: '01G9ZWEBTF7MPY95A1ARJPW5X8', name: 'Anonymous, Law Student', chapter: 'Durham', year: 2021, quote: 'I really liked the philosophy behind it of making donating a part of celebration rather than viewing it as something overly-sacrificial.',
  },
  {
    id: '01G9ZWEBTGKXWV5K9NPDCHACAW', name: 'Tyler Hassan, Anatomy Student', chapter: 'Glasgow', year: 2021, quote: 'It’s a great, new and unique initiative I haven’t seen before and knew I had to be involved !',
  },
  {
    id: '01G9ZWEBTGBNXE6KEPMER5B9W7', name: 'Amy Connor, Scottish Literature Student', chapter: 'Glasgow', year: 2021, quote: 'I joined Raise as I had heard about it from a friend and it seemed like a great opportunity to get involved with a good cause at the uni and meet new people.',
  },
  {
    id: '01G9ZWEBTGXPB86XFXCRVVBFE2', name: 'Orestis Savva', chapter: 'Glasgow', year: 2021, quote: 'I joined Raise because its values and philosophy are focused into making a positive impact.',
  },
  {
    id: '01G9ZWEBTG8SBB11KNM5BWT7GQ', name: 'Jessica Sword, Genetics Student', chapter: 'Glasgow', year: 2021, quote: 'I decided to join raise to be part of an amazing organisation that can have a massive impact protecting lives, while also being part of such an incredible community',
  },
  {
    id: '01G9ZWEBTMCF6GZZD72TAGAMWV', name: 'Anonymous, Chemistry (PhD) Student', chapter: 'Cambridge', year: 2021,
  },
  {
    id: '01G9ZWEBTM9S8E82Y0FR75X36F', name: 'Esther Abelian, Medicine Student', chapter: 'Cambridge', year: 2021,
  },
  {
    id: '01G9ZWEBTGM0P0HAPN1A6288C9', name: 'Evie Clarke, Pharmacology Student', chapter: 'Glasgow', year: 2021, quote: "I joined Raise because it is the perfect opportunity to make a difference, and I loved the ethos and message it spreads. I was also very keen to get involved with another community at university, and I've been so lucky to have met so many great people because of it.",
  },
  {
    id: '01G9ZWEBTFHCB8P4CK0WKTC16V', name: 'Emma Riley, History Student', chapter: 'Durham', year: 2021, quote: 'The mission aligned with my personal beliefs and supported a charity I have supported in the past.',
  },
  {
    id: '01G9ZWEBTMJM2ZGTYS79GHAMY2', name: 'Anonymous, English Student', chapter: 'Cambridge', year: 2021, quote: "I'm interested in helping people who need it, and meeting other people with similar interests. We're privileged to be here, and should do something to pass that forward to those who aren't.",
  },
  {
    id: '01G9ZWEBTMB93BMVBEP832RJ0S', name: 'Anonymous, Medicine Student', chapter: 'Cambridge', year: 2021,
  },
];

const CHAPTERS = new Set([...ALL_ENTRIES.map((e) => e.chapter)]);
const YEARS = new Set([...ALL_ENTRIES.map((e) => e.year.toString())]);

const YearbookPage: React.FC<{ brand?: Brand }> = ({ brand }) => {
  const formMethods = useForm<{ chapterFilter: string, yearFilter: string }>({
    defaultValues: {
      chapterFilter: 'All chapters',
      yearFilter: 'All years',
    },
  });

  const chapterFilterValue = formMethods.watch('chapterFilter');
  const yearFilterValue = formMethods.watch('yearFilter');
  const filteredEntries = ALL_ENTRIES.filter((e) => (chapterFilterValue === 'All chapters' || e.chapter === chapterFilterValue) && (yearFilterValue === 'All years' || e.year.toString() === yearFilterValue));

  return (
    <Page brand={brand}>
      <Helmet>
        <meta name="robots" content="noindex" />
        <title>
          {brand}
          : Yearbook
        </title>
        <meta property="og:title" content={`${brand}: Yearbook`} />
      </Helmet>

      <Navigation
        left={[
          { text: '< back to main site', href: '/' },
        ]}
        right={[
        ]}
      />
      <Section className="px-8">
        <IntroStats
          title={`${brand} Yearbook`}
          tagline={`${brand} wouldn't be the success it is today without its amazing community! This yearbook celebrates their impact, which together is an incredible:`}
          statistics={{
            years: 5,
            students: 2099,
            raised: 382739,
            protected: 455285,
          }}
        />
      </Section>

      <Section>
        <SectionTitle>Members</SectionTitle>
        <div className="grid grid-cols-2 gap-2 text-left">
          <FormProvider {...formMethods}>
            <LabelledInput id="chapterFilter" label={<span className="text-white">Chapter</span>} type="select" options={[...CHAPTERS, 'All chapters']} {...formMethods.register('chapterFilter')} />
            <LabelledInput id="yearFilter" label={<span className="text-white">Year</span>} type="select" options={[...YEARS, 'All years']} {...formMethods.register('yearFilter')} />
          </FormProvider>
        </div>
        <div className="">
          {filteredEntries.map((m, i) => (
            <Quote key={m.id} by={`${m.name}, ${m.chapter} '${m.year.toString().slice(2)}`} headshotSrc={m.img} imagePlacement={i % 4 <= 1 ? 'left' : 'right'} className="mt-4 p-8 bg-raise-red rounded-lg min-h-[10rem]">
              {m.quote}
            </Quote>
          ))}
        </div>
      </Section>

      <Section id="faq">
        <SectionTitle>FAQs</SectionTitle>
        <FAQs>
          <FAQ title={`How can I stay involved with ${brand}?`}>
            <p>
              We'd love to keep in touch, and continue celebrating positive, deliberate and effective giving as you go out and do exciting things! Come and join
              <Link href="/alumni/">our alumni community</Link>
              {' '}
              to stay up to date with the latest news, events and opportunities.
            </p>
          </FAQ>

          <FAQ title={`Where do I learn more about ${brand}?`}>
            <p>
              We're excited you're interested in
              {brand}
              ! For more details on what it is we do, see
              <Link href="/">our main website</Link>
              !
            </p>
          </FAQ>

          <FAQ title="What's the difference between MWA and Raise?">
            <p>The Raise movement started in Cambridge, where it was known as May Week Alternative (MWA). We've since started other chapters, expanding to other universities and beyond! These are branded under the 'Raise' name to work better outside Cambridge but share the same philosophy and structure.</p>
          </FAQ>

          <FAQ title="How can I get added or removed from the yearbook?">
            <p>
              If you'd like to be added or removed,
              <Link href="../#contact">contact us</Link>
              {' '}
              with your details and we'd be happy to help! Similarly, if you'd like to tweak your quote, change your name or anything else do let us know.
            </p>
            <p>
              If you're on this page, it's because you previously provided your personal details and consented to being added to the yearbook. To get a complete picture of how we use your personal data, or understand how to exercise your rights under data protection legislation see
              <Link href="/privacy/">our privacy policy</Link>
              .
            </p>
          </FAQ>
        </FAQs>
      </Section>

      <Footer />
    </Page>
  );
};

export default YearbookPage;
